### ISSUE TITLE
Migrate away from travis-ci.org

### ISSUE THREAD

**Issue by slonopotamus** [i-net-software/SetupBuilder#101]
travis-ci.**org** is dead since June 15 and no longer runs builds. 

Alternatives include:
* travis-ci.**com**. A one-click migration, but. Note that by default you will only get a one-time free build quota. Additional build quota is possibly available upon request, though conditions are not clear.
* GitHub Actions. Absolutely free for public repos, tightly integrates with the rest of GitHub, etc. I know that *many* OSS projects migrated there when Travis announced that travis-ci.**org** will fade away. If you need some help with migration, I could do that.
* GitLab CI. Would make sense if your repo was hosted on GitHub.
* Others are much less known and I don't have any good reasons to suggest them.

**Comment by Horcrux7** [comment]
Thanks for pointing out to this problem. We have oversee this.

We have migrate to travis-ci.com for now. I have also request for free quota for the OSS projects. I wait on the response now.

**Comment by Horcrux7** [comment]
The travis support is curios. We think about a migration to Github Actions now.
