### ISSUE TITLE
Latest release publishing

### ISSUE THREAD

**Issue by jvmlet** [i-net-software/SetupBuilder#102]
Hello 
I'm trying to migrate my project to gradle `7.x`  and the  build fails with 
```
org.gradle.internal.execution.WorkValidationException: Some problems were found with the configuration of task ':msi' (type 'Msi').
  - In plugin 'de.inetsoftware.setupbuilder' type 'com.inet.gradle.setup.msi.Msi' property '64Bit' is missing an input or output annotation.
```

Same error for all other properties as well. 
I see that `@Input` annotation was added for all getters in master branch, would you please publish the release /snapshot to allow to proceed further  with gradle 7 migration ?
Thanks

**Comment by Horcrux7** [comment]
Version x.x.10 is released now.

**Comment by jvmlet** [comment]
Thanks, @Horcrux7 
I've opened also #103 with PR  #104 as starting point
