### ISSUE TITLE
Gradle kts 7.2 dmg build throws exception

### ISSUE THREAD

**Issue by Hero9909** [i-net-software/SetupBuilder#107]
By running your plugin with gradle 7.2 and plugin version 7.2.13, an exception is thrown that the property codeSigning of type Dmg is missing an input or output annotation.

I think i might miss an option thats required. 
Whats the minimal options that i need to build a dmg file? Excluding general options of setupBuilder, of cause.

**Comment by Horcrux7** [comment]
Can you try this fix?

**Comment by xian** [comment]
@Horcrux7 — Any chance of a release including these fixes? Thanks!

**Comment by Horcrux7** [comment]
We will make a new release in some days.

**Comment by Horcrux7** [comment]
There is a new release. Sorry for the delay. There was problems with Travis.
