### ISSUE TITLE
Cannot get customUI example in testBuilds folder to work

### ISSUE THREAD

**Issue by engaric** [i-net-software/SetupBuilder#111]
Added the ui block from template.wxs to my preexisting template and adding fragementDlg.wxs as an external reference.
When I run the created installer the sequence is as follows.
Using Next buttons WelcomeDlg -> DirectoryDlg -> VerifyDlg
Using Back buttons VerifyDlg-> CustomDlg -> DirectoryDlg  -> WelcomeDlg

I am using Wix Toolkit 3.11 and SetupBuilder/MSI 7.2.13
I intend to replace the CustomDlg with the standard WixUI CustomizeDlg to allow for specific elements of the application to be selected but was trying the basic example first.

**Comment by Horcrux7** [comment]
What is the problem with it? What is wrong on the generated *.wxs file? Why you think this is a SetupBuilder problem and not related to your template.wxs?

We can't give support for any Wix Toolset feature.

**Comment by engaric** [comment]
Sorry I though I had updated this a long time ago. I cannot eeven remember what the resolution was but it was our use that was incorrect.
