### ISSUE TITLE
Problem with lazy evaluation of war.archiveFileName

### ISSUE THREAD

**Issue by Robert-Adelard** [i-net-software/SetupBuilder#114]
Hello,

I am upgrading my application from Gradle 3.5 to Gradle 7.2 and have run into a problem caused by a change in the War Plugin API. Previously, `war.archiveFileName` was a `String`, but now it is a `Property<String>`.

As a result, the following extract from the `setupBuilder` section of my Gradle build file has stopped working:

```
setupBuilder {
    // include war file for application
    from( "${buildDir}/libs" ) {
        include "${war.archiveFileName}"
    }
}
```

I now get a "No files selected" exception. The solution is to add an explicit call to `get()` but this doesn't seem very elegant, and I am wondering if there is a better approach, for example, whether it is possible to pass the `war.archiveFileName` property to `include` so that it is evaluated by the SetupBuilder plugin itself.

I'd appreciate your comments.

Thanks,

Robert

**Comment by Horcrux7** [comment]
I thing the [Gradle forum](https://discuss.gradle.org/) or [stackoverflow ](https://stackoverflow.com/) is a better place to ask questions over  standard task like `war`.

Where the war.archiveFileName come from? Is it not init from a global property? Should the filename static? Then you can replace it with a constant string.
