### ISSUE TITLE
plugin [id "de.inetsoftware.setupbuilder" version "7.2.16"] was not found in any of the following sources:

### ISSUE THREAD

**Issue by Papa-26** [i-net-software/SetupBuilder#115]
The plugin works great in Linux, but in my Windows 10 laptop I got the above error. 
Gradle 7.6 with Intellij

**Comment by Papa-26** [comment]
It is not a sources problem. for, without the plugin, the jpackage build nicely produces .exe, runtime etc. Together they run on the Laptop. I did  wonder about timing though. I connected the laptop with an internet cable instead of wifi, but that made no difference. The laptop is an old, cheap Asus running win10 Home (but the latest update). Also, my network has no difficulty finding the plugin, since my very fast Linux machine runs off the same network.

**Comment by Horcrux7** [comment]
This answer nothing. You need a person with a glass sphere for help. 

If you open an issue on one of the both suggested platforms you should write more details, like your Gradle script, the output from the debug log, etc.

**Comment by Horcrux7** [comment]
@Papa-26 I can not answer you per email:

```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [ralph.bloch@bell.net](mailto:ralph.bloch@bell.net)
    host mx.bell.net [209.71.208.7]
    SMTP error from remote mail server after initial connection:
    554 Access Denied


Reporting-MTA: dns; www353.your-server.de

Action: failed
Final-Recipient: [rfc822;ralph.bloch@bell.net](mailto:rfc822;ralph.bloch@bell.net)
Status: 5.0.0
Remote-MTA: dns; mx.bell.net
Diagnostic-Code: smtp; 554 Access Denied
```

**Comment by Horcrux7** [comment]
Meine Mail:

> Hallo Herr Bloch,
> 
> Steht das irgendwo in der Doku mit dem Snapshot. Wenn ja können sie mir sagen wo?
> 
> Auch wenn ich mit anderen ein Plugin für Gradle geschrieben, ist das nicht mein täglich Brot. Darum kann ich auch kein allgemeinen Support dafür geben. Im Gegenteil, ich beanspruche auch die Community für solche Fragen. Aber egal, wo sie fragen, sollten Sie Details des Problems schreiben. Niemand hat Lust erst nach Details zu fragen. Lieber zuviel als zu wenig. Hätten Sie ihr Gradle Script mit dem Snapshot gepostet, hätte man den Fehler gesehen oder nachstellen können. Ohne dies Information bleibt kein Ansatz für Hilfe.
> 
> Die DSL des SetupBuilders folgt der Datei Syntax von Gradle, Stichworte sind also Gradle, Files, Copy
> 
> z.B.:
> 
> https://docs.gradle.org/current/userguide/working_with_files.html
> https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html
> 
> MfG
> 
> Volker Berlin 
>
