### ISSUE TITLE
Problem building desktop application

### ISSUE THREAD

**Issue by Robert-Adelard** [i-net-software/SetupBuilder#117]
Hello,

I am upgrading a Grails application that uses SetupBuilder from Grails 3.2.x to Grails 5.2.y. The old version of the application used Gradle 3 and SetupBuilder 3.4.3 - the new version uses Gradle 7 and SetupBuilder 7.2.16. 

The old configuration no longer builds an executable war file - I get the following error message:

```
Error: Could not find or load main class org.springframework.boot.loader.WarLauncher
```

I assume this is because Gradle 7 or SetupBuilder 7 require a slightly different configuration for a desktop application, as per the instructions on the Wiki page:

[https://github.com/i-net-software/SetupBuilder/wiki/How-to-create-setup-of-desktop-application-using-with-the-Gradle-Application-plugin](https://github.com/i-net-software/SetupBuilder/wiki/How-to-create-setup-of-desktop-application-using-with-the-Gradle-Application-plugin)

However, when I adapted my `build.gradle` configuration accordingly, I got the following error message:

```
Execution failed for task ':application:jar'.
> Entry messages.properties is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

What am I doing wrong?

Thanks,

Robert

**Comment by Horcrux7** [comment]
> ```
> Execution failed for task ':application:jar'.
> > Entry messages.properties is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
> ```

This is a problem of the different Gradle version. Gradle 3 has ignore if you add multiple time the same file. Now you must prevent this or how to handle it. For example:

    copy {
        duplicatesStrategy DuplicatesStrategy.WARN
    }
    task jar {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }

Because this is not SetupBuilder related you can get better help in the Gradle forum and not here.

**Comment by Robert-Adelard** [comment]
Thank you @Horcrux7 - it wasn't clear whether this was a Gradle issue, a SetupBuilder issue, or a problem caused by the interaction between the two.
