### ISSUE TITLE
version release

### ISSUE THREAD

**Issue by knguyen99** [i-net-software/SetupBuilder#120]
when is v17 going to be released? i need the update for a current project

**Comment by knguyen99** [comment]
@Horcrux7

**Comment by Horcrux7** [comment]
I will see that I can publish a new version in the next days.

**Comment by Horcrux7** [comment]
Version v17 was released.

**Comment by Horcrux7** [comment]
No, after deploy an update of an existing version is not possible. We can only deploy a new version. That the previous question if you have test it.

**Comment by Horcrux7** [comment]
Now released
