### ISSUE TITLE
Support for Gradle 8.+ - missing plugin version

### ISSUE THREAD

**Issue by tomerarazy** [i-net-software/SetupBuilder#125]
I've upgraded my project to use Gradle 8.5, and it seems there is no matching version for that.
Using the `SetupBuilderVersion.gradle` to determine the version I'm getting `8.0.+` but it seems that the latest released version is `7.2.20`.
Am I missing something here? Because from reading the code it does seem to support Gradle 8.+

**Comment by Horcrux7** [comment]
A version 8.4.21 is deployed and should be compatible with Gradle >= 8.4.

**Comment by tomerarazy** [comment]
Thanks for the quick response and solution @Horcrux7
