### ISSUE TITLE
Compile error if bundleJre is a file path?

### ISSUE THREAD

**Issue by Robert-Adelard** [i-net-software/SetupBuilder#126]
Hello,

If I set `bundleJre` to a version number, for example,

`bundleJre = "11.0.22.7"`

my Gradle script works fine.

If I set `bundleJre` to a file path, for example:

`bundleJre = "C:\Program Files (x86)\Java\jre-11.0.22.7-hotspot"`

I get a compile error:
```
startup failed:
build file C:\Users\...\application\build.gradle: Unexpected input: '{' at line NNN, column 14.
setupBuilder { 
             ^
1 error
```
Is this a bug or am I doing something wrong?

Thanks

Robert

**Comment by Horcrux7** [comment]
Backslashes must be escaped in Gradle as in Java. Alternatively, you can also use slashes in Windows. Java and Gradle can use these as path delimiters.
