### ISSUE TITLE
MSI installer perUser requires HKLM registry permissions

### ISSUE THREAD

**Issue by conapi-stefan** [i-net-software/SetupBuilder#127]
I am using a wxsTemplate to set the install dir to the users local app data folder:
```
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
  <Product>
    <SetProperty Id="INSTALLDIR" Value="[LocalAppDataFolder]MyApp" Sequence="first" Before="CostFinalize">NOT Installed AND NOT INSTALLDIR</SetProperty>
  </Product>
</Wix>
```
The installScope is per user:
```
msi{
...
installScope = 'perUser'
...
}
```
The resulting installer defaults to the correct folder but tries to write to the HKLM registry.

The built wxs file contains two HKLM entries:
```
<RegistryKey ForceDeleteOnUninstall="yes" Id="install_path_reg" Key="Software\MyApp\LastInstallDir" Root="HKLM">
...
<RegistrySearch Id="SearchInstallDir" Key="Software\MyApp\LastInstallDir" Root="HKLM" Type="directory"/>
```

My goal is to allow the user to install without any Administrator permissions. 
I guess the HKLM registry entries are the only hurdle here. Can these be redirected to HKCU?

**Comment by Horcrux7** [comment]
Which registry entries are this? Do you have a snippet of wxs file with the two entries?

**Comment by Horcrux7** [comment]
Do you have try to define it in the wxsTemplate?

If you add the follow in the correct XML hierarchy this should work:

```
<RegistryKey Id="install_path_reg" Root="HKCU">
<RegistrySearch Id="SearchInstallDir" Root="HKCU"/>
```
Check that the XML is valid based on the generated wsx file. After building a new setup check that the Root attribute was not changed. Then test your installer and me if this solve your problem.

A fix in the SetupBuilder should be possible but will need some time.

**Comment by conapi-stefan** [comment]
Thanks a lot for the swift reply and solution! We can close this unless you want to also think a fix in the SetupBuilder is needed.
It works now and below is the template I use in case anybody else needs this:

```
<?xml version="1.0" encoding="windows-1252"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
  <Product>
    <SetProperty Id="INSTALLDIR" Value="[LocalAppDataFolder]conapi\MyApp" Sequence="first" Before="CostFinalize">NOT Installed AND NOT INSTALLDIR</SetProperty>

    <DirectoryRef Id="INSTALLDIR">
      <Component Id="install_path">
        <RegistryKey ForceDeleteOnUninstall="yes" Id="install_path_reg" Key="Software\conapi gmbh\MyApp\LastInstallDir" Root="HKCU">
          <RegistryValue Type="string" Value="[INSTALLDIR]"/>
        </RegistryKey>
      </Component>
    </DirectoryRef>

    <Property Id="INSTALLDIR">
      <RegistrySearch Id="SearchInstallDir" Key="Software\conapi gmbh\MyApp\LastInstallDir" Root="HKCU" Type="directory"/>
    </Property>
    
  </Product>
</Wix>

```

**Comment by Horcrux7** [comment]
Thanks for the feedback. I have fix this for future SetupBuilder version. Currently is no plan for the next release.
