### ISSUE TITLE
rollback service restart

### ISSUE THREAD

**Issue by knguyen99** [i-net-software/SetupBuilder#129]
im having an issue when performing a failed msi upgrade and rollback occurs, the service that was previously installed does not restart and cannot start from services application. is there a fix for this?

i can install the service manually again by clicking on the service gui exe located in the install directory and installing but cannot do it automatically through the msi.

**Comment by Horcrux7** [comment]
Sounds like that the registry keys of the Java service was not rewritten on rollback. I have no idea why this occur and how to fix it. The `msiexec` is a Microsoft tool and has some magic behavior.

Can be that the `WiX toolset` support can help based on the generated template.wxs. https://wixtoolset.org/docs/gethelp/

If you want try some modifications on the template.wxs it is describe in the wiki: https://github.com/i-net-software/SetupBuilder/wiki/Create-a-MSI-with-WXS-template

If you found a solution then you can post it here. Can be possible that we patch the `SetupBuilder`.

**Comment by knguyen99** [comment]
solution: create a csharp custom action that recreates missing apache procrun registry key on rollback
