### ISSUE TITLE
bundleJre for multiple architectures supported?

### ISSUE THREAD

**Issue by conapi-stefan** [i-net-software/SetupBuilder#130]
We use setupBuilder to build msi and DMG installers.

For MSI we so far ran the build on a Windows machine.

For MacOS we run on an ARM64 platform and have only arm64 defined as architecture.

We wonder whether it is possible to use "x86_64", "arm64" as architecture but have different JREs to bundle per architecture. 

Ideally we want to be able to build all installers on any machine, not sure if there is a sample that would show this.

```
 if(isMac) {
        bundleJre = "/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home"
       ....
 }

...

dmg {
     architecture = ["arm64"]
    jreIncludes = [ '**' ]
    jreExcludes = [ '**/legal/**' ]

...
}

```

**Comment by gamma** [comment]
Hi, the default architecture is ["x86_64", "arm64"] which will be used for the `LSArchitecturePriority` to indicate which platforms are supported by the application. It is not possible to create a unified installer for both platforms with different JVMs.

You have to create an additional build job for the second architecture and provide the correct JRE for that architecture.

**Comment by conapi-stefan** [comment]
Ok, thanks for the clarification. Ended up having dedicated tasks now each bunlding a different JRE.

gradle dmg_arm64
gradle dmg_x86_64
