### ISSUE TITLE
How do you use custom pre/post scripts for .deb and .rpm packages

### ISSUE THREAD

**Issue by pitabwire** [i-net-software/SetupBuilder#19]
While attempting to package a java application at https://github.com/caricah/iotracah I just decided to switch to your setup builder which so far is flawless. I would however like to use my own created post/pre install and remove scripts and can't find a simple way to customize them. 

Could you guide me on what to do.

**Comment by Horcrux7** [comment]
Do you means some things like this?

    setupBuilder.runAfter{
       mainJar = "abc.jar"
       mainClass = "abc.After"
    }
or

    setupBuilder.runAfter{
       executeable = "abc.bat"
    }

details to the propeties can you find at: 
https://github.com/i-net-software/SetupBuilder/blob/master/src/com/inet/gradle/setup/DesktopStarter.java and
https://github.com/i-net-software/SetupBuilder/blob/master/src/com/inet/gradle/setup/Application.java

**Comment by pitabwire** [comment]
Well, I was packaging a .deb [unix] and would like to use my own preinst, postinst, prerm and postrm scripts. However the plugin automatically generates these for me, the functionality is somewhat limiting in my case as there are other steps my application needs to execute.

https://github.com/i-net-software/SetupBuilder/blob/master/src/com/inet/gradle/setup/deb/Deb.java does not have variables I can use to customize these values too.

**Comment by sheidrich1978** [comment]
I have added the preinst, postinst, prerm and the postrm variables in the next build. 
You can add your own script by adding them to the gradle script like:

    deb {
        preinst = "<first line>"
        preinst = "<second line>"
    }

or 

    deb {
        preinst = "<first line>\n<second line>\n<third line>"
    }


Hope this helps.

**Comment by Horcrux7** [comment]
Version 1.4.7 is available.

**Comment by pitabwire** [comment]
@sheidrich1978 thanks for the effort. I have finally managed to test the changes in 1.4.7.
The desired result was a complete overwrite of any specified files. However the changes divert to the custom scripts while maintaining the built in flow. If you have time please take a look at the build file in the project  https://github.com/caricah/iotracah and compare the output .deb for ./gradlew  deb and ./gradlew  buildDeb. forget about the lintian exceptions. 

I would really like to use setup builder because of its support for windows and mac. Also particularly for the .deb build it executes the lintian test after finishing.
