### ISSUE TITLE
Wrong Plugin Version number in Readme.md

### ISSUE THREAD

**Issue by MatthiasEdelhoff** [i-net-software/SetupBuilder#25]
The lines 
| all       | Plugin Version <= 2.5 Gradle 2.3 - 2.11                              |
| all       | Plugin Version >= 2.6 Gradle 2.12 or higher                          |
should probably read
| all       | Plugin Version <= 1.5 Gradle 2.3 - 2.11                              |
| all       | Plugin Version >= 1.6 Gradle 2.12 or higher                          |

Also as 1.5 is the latest released version, which does not work with latest gradle releases, you maybe want to highlight that fact. 
For others: If you get this wrong expect
> org.gradle.process.internal.DefaultExecAction.<init>(Lorg/gradle/api/internal/file/FileResolver;

**Comment by Horcrux7** [comment]
Thanks for reporting this. This was a mix with the gradle version. We have correct this.
We have also publish version 1.5.1 and version 1.6 now.
