### ISSUE TITLE
baseName , licence these property are unknown

### ISSUE THREAD

**Issue by ajaiswal595** [i-net-software/SetupBuilder#26]
While Executing i am getting the error:

* Where:
Build file 'G:\GradlePractise\msi\build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'msi'.
> Could not set unknown property 'baseName' for object of type com.inet.gradle.setup.SetupBuilder.

build.gradle
----------------
plugins {
    id "de.inetsoftware.setupbuilder" version "1.5.0"
}

setupBuilder {
    vendor = 'i-net software'
    application = "SetupBuilder Plugin"
    baseName = "SetupBuilder"
    version = '1.0'
    licenseFile = 'license.txt'
    // icons in different sizes for different usage. you can also use a single *.ico or *.icns file
    icons = ['icon16.png', 'icon32.png', 'icon48.png', 'icon128.png']
    // all files for all platforms
    from( 'source' ) {
        include 'files/*.jar'
    }
    bundleJre = 1.8
}

setupBuilder {
    vendor = 'i-net software'
    application = "SetupBuilder Plugin"
    //baseName = "SetupBuilder"
    version = '1.0'
    licenseFile = 'license.txt'
   
    from( 'source' ) {
        include 'files/*.java'
    }
    bundleJre = 1.8
}

msi {
    // files only for the Windows platform
    from( 'windows' ) {
        include 'foo.exe'
        rename { 'bar.exe' }
    }
}

What is going wrong.

**Comment by Horcrux7** [comment]
Thanks for reporting this problems.
baseName is now named appIdentifier. licenseFile was fixed. In the version 1.5 you can it used only without equals.

**Comment by ajaiswal595** [comment]
I am binding the code in task a

plugins {
    id "de.inetsoftware.setupbuilder" version "1.5.0"
}


task a<<{
setupBuilder {
    vendor = 'i-net software'
    application = "SetupBuilder Plugin"
    appIdentifier = "SetupBuilder"
    version = '1.0'
    licenseFile  'license.txt'
   
    from( 'source' ) {
        include 'files/*.java'
    }
    bundleJre = 1.8
}




msi {
    // files only for the Windows platform
    from( 'windows' ) {
        include 'foo.exe'
        rename { 'bar.exe' }
    }
}
}

G:\GradlePractise\msi>gradle a
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html.
setting default Destination to: G:\GradlePractise\msi\build\distributions
:a

BUILD SUCCESSFUL

Total time: 10.883 secs
G:\GradlePractise\msi>


but i am not getting any thing even G:\GradlePractise\msi\build\distributions is not created.

If you can place one working example to we can get enough confidence to use this plugin.
Thank you

**Comment by Horcrux7** [comment]
It look like that you does not have run the task "msi" or any of the other task for the other OS. The task "a" is not required. Move the setupBuilder into the root like the base sample and call:

`gradle msi`

To build a msi file.

**Comment by ajaiswal595** [comment]
I am working on windows machine.
I am not getting what is the base sameple.




plugins {
    id "de.inetsoftware.setupbuilder" version "1.5.0"
}



setupBuilder {
    vendor = 'i-net software'
    application = "SetupBuilder Plugin"
    appIdentifier = "SetupBuilder"
    version = '1.0'
    licenseFile  'license.txt'
   
    from( 'source' ) {
        include 'src'
    }
    bundleJre = 1.8
}




msi {
    // files only for the Windows platform
    from( 'windows' ) {
        include 'foo.exe'
        rename { 'bar.exe' }
    }
}




G:\GradlePractise\msi>gradle msi --info
Starting process 'command 'C:\Program Files\Java\jdk1.8.0_91\bin\java.exe''. Working directory: G:\GradlePractise\msi Command: C:\Program Files\Java\jdk1.8.0_91\bin\java.exe -version
Successfully started process 'command 'C:\Program Files\Java\jdk1.8.0_91\bin\java.exe''
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html.
Starting process 'command 'C:\Program Files\Java\jdk1.8.0_91\bin\java.exe''. Working directory: G:\GradlePractise\msi Command: C:\Program Files\Java\jdk1.8.0_91\bin\java.exe -version
Successfully started process 'command 'C:\Program Files\Java\jdk1.8.0_91\bin\java.exe''
Starting daemon process: workingDir = C:\Users\LIPLADMIN\.gradle\daemon\2.14, daemonArgs: [C:\Program Files\Java\jdk1.8.0_91\bin\java.exe, -XX:MaxPermSize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Xmx1024m, -Dfile.encoding=windows-1252, -Duser.country=US, -Duser.language=en, -Duser.variant, -cp, C:\gradle-2.14\lib\gradle-launcher-2.14.jar, org.gradle.launcher.daemon.bootstrap.GradleDaemon, 2.14]
Starting process 'Gradle build daemon'. Working directory: C:\Users\LIPLADMIN\.gradle\daemon\2.14 Command: C:\Program Files\Java\jdk1.8.0_91\bin\java.exe -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\gradle-2.14\lib\gradle-launcher-2.14.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 2.14
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 2.802 secs.
Connected to daemon DaemonInfo{pid=9036, address=[f1f01fe8-6c3a-4601-b8bc-1e0a1853b761 port:62040, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], idle=false, lastBusy=1469091331827, context=DefaultDaemonContext[uid=9390316f-b058-4631-9fb0-d7a69c1776dc,javaHome=C:\Program Files\Java\jdk1.8.0_91,daemonRegistryDir=C:\Users\LIPLADMIN\.gradle\daemon,pid=9036,idleTimeout=120000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]}. Dispatching request BuildAndStop{id=2f53a806-0d5b-4e05-bf93-c0761178bb19.1, currentDir=G:\GradlePractise\msi}.
Received result org.gradle.launcher.daemon.protocol.BuildStarted@52dec7eb from daemon DaemonInfo{pid=9036, address=[f1f01fe8-6c3a-4601-b8bc-1e0a1853b761 port:62040, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], idle=false, lastBusy=1469091331827, context=DefaultDaemonContext[uid=9390316f-b058-4631-9fb0-d7a69c1776dc,javaHome=C:\Program Files\Java\jdk1.8.0_91,daemonRegistryDir=C:\Users\LIPLADMIN\.gradle\daemon,pid=9036,idleTimeout=120000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be starting).
The client will now receive all logging from the daemon (pid: 9036). The daemon log file: C:\Users\LIPLADMIN\.gradle\daemon\2.14\daemon-9036.out.log
Executing build with daemon context: DefaultDaemonContext[uid=9390316f-b058-4631-9fb0-d7a69c1776dc,javaHome=C:\Program Files\Java\jdk1.8.0_91,daemonRegistryDir=C:\Users\LIPLADMIN\.gradle\daemon,pid=9036,idleTimeout=120000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]
Starting Build
Settings evaluated using settings file 'G:\master\settings.gradle'.
Projects loaded. Root project using build file 'G:\GradlePractise\msi\build.gradle'.
Included projects: [root project 'msi']
Evaluating root project 'msi' using build file 'G:\GradlePractise\msi\build.gradle'.
setting default Destination to: G:\GradlePractise\msi\build\distributions
All projects evaluated.
Selected primary task 'msi' from project :
Tasks to be executed: [task ':msi']
Creating In-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\fileHashes.bin: MaxSize{400000}
Creating In-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\treeSnapshots.bin: MaxSize{20000}
Creating In-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\treeSnapshotUsage.bin: MaxSize{20000}
Creating In-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\fileSnapshotsToTreeSnapshotsIndex.bin: MaxSize{10000}
Creating In-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\fileSnapshots.bin: MaxSize{10000}
Creating In-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\taskArtifacts.bin: MaxSize{2000}
:msi (Thread[Daemon worker,5,main]) started.
:msi
Invalidating in-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\fileHashes.bin
Invalidating in-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\treeSnapshotUsage.bin
Invalidating in-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\fileSnapshotsToTreeSnapshotsIndex.bin
Invalidating in-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\treeSnapshots.bin
Invalidating in-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\fileSnapshots.bin
Invalidating in-memory cache of G:\GradlePractise\msi\.gradle\2.14\taskArtifacts\taskArtifacts.bin
Executing task ':msi' (up-to-date check took 0.036 secs) due to:
  No history is available.
:msi FAILED
:msi (Thread[Daemon worker,5,main]) completed. Took 0.212 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':msi'.
> No files selected by: [source] --> . This means that there are files missing or your 'from' method in your gradle script is wrong. If an empty 'from' is valid then disable the check with 'setupBuilder.failOnEmptyFrom = false'

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 11.231 secs
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':msi'.] from daemon DaemonInfo{pid=9036, address=[f1f01fe8-6c3a-4601-b8bc-1e0a1853b761 port:62040, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], idle=false, lastBusy=1469091331827, context=DefaultDaemonContext[uid=9390316f-b058-4631-9fb0-d7a69c1776dc,javaHome=C:\Program Files\Java\jdk1.8.0_91,daemonRegistryDir=C:\Users\LIPLADMIN\.gradle\daemon,pid=9036,idleTimeout=120000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done)







please upload one working example with folder structure

Thank you

**Comment by Horcrux7** [comment]
What you does not understand on this error message?

> No files selected by: [source] --> . This means that there are files missing or your 'from' method in your gradle script is wrong. If an empty 'from' is valid then disable the check with 'setupBuilder.failOnEmptyFrom = false'

The follow block match no files:
```
from( 'source' ) {
    include 'src'
}
```
This means your filter criteria in this from block is wrong. No files will be added to the setup. Why you add this block to your build script? Is it an error? If you expected that selection blocks does not select files then you can set the flag setupBuilder.failOnEmptyFrom = false to ignore empty selections.

You can write it
```
setupBuilder.failOnEmptyFrom = false
```
or
```
setupBuilder {
    failOnEmptyFrom = false
}
```
