### ISSUE TITLE
Request for sample project using setup builder with documentation

### ISSUE THREAD

**Issue by Leejjon** [i-net-software/SetupBuilder#27]
Hey,

It might be me just being a gradle noob, but I have been trying to add this plugin by adding the stuff in the readme file to my build.gradle. I want to generate a .msi file. My guess was that I have to run "gradle msi" to start generating an installer file, but this error occurs.
`Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/file/PathToFileResolver
        at com.inet.gradle.setup.msi.Msi.build(Msi.java:74)
        at com.inet.gradle.setup.AbstractTask.action(AbstractTask.java:88)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 61 more
Caused by: java.lang.ClassNotFoundException: org.gradle.internal.file.PathToFileResolver
        ... 71 more
`

Now this might be totally me having my gradle file wrong ([gradle file](http://pastebin.com/3r9y1GQ2)). But I can't really seem to run the test application that is included either when I cloned this project from github. I managed to build the entire plugin, but not to generate a working msi file from the gradle files in the testbuilds. 

It would be nice to have a separate hello world java project using the setupBuilder gradle plugin with some basic instructions on how to run it, and link to it from the wiki/readme. I'm sure me and other devs could easily figure out how to use this plugin from playing around with a starting point that works.

**Comment by Leejjon** [comment]
Step by step guide how to build this project (I just wrote down exactly what I did to get it working)

Clone the SetupBuilder project in your C:\Users\Yourname\IdeaProjects\SetupBuilder folder using sourcetree or git via the commandline.

Install and install the Wix toolset (I seem to have both WiX Toolset v3.10.3.3007 and v4.0.4305.0 installed, not sure which one it uses:
http://wixtoolset.org/releases/

Download Gradle 2.12 (maybe newer versions work too, but that was the one that was mentioned in the readme) [here](https://gradle.org/gradle-download/). Gradle 3.0 does not seem to work.

Unzip it somewhere on your drive and set up your %GRADLE_HOME% environment variable (mine was C:\gradle\gradle-2.12), and add it to your path variable:
https://docs.gradle.org/current/userguide/installation.html?_ga=1.53018472.1319905455.1453751567

Open cmd.exe and type gradle, you should see something happening instead of "'gradle' is not recognized as an internal or external command operable program or batch file.".

Open IntelliJ (I'm using 15.0.6), click open project (or import project) and select the SetupBuilder folder you've cloned. Select gradle. Select "Use local gradle distribution", and select your gradle home you've also set in your %GRADLE_HOME% environment variable. Make sure you're using at least a JDK8.

Open up a terminal (in intellij, View->Tool Windows->Terminal). Run "gradle build" and it should say "BUILD SUCCESFUL". If you try this with gradle3.0 installed you'll get an error.

Now by default it has placed a jar in the local maven repo, which it creates in the root of your IdeaProjects folder. Mine was: C:\Users\Leejjon\IdeaProjects\repo\de\inetsoftware\SetupBuilder\1.6.0-SNAPSHOT

Now rename the testBuilds/setupBuilder.gradle to build.gradle, and navigate into the testBuilds folder in your terminal by typing "cd testBuilds". 

Modify the version of the classpath entry:
`dependencies {
        classpath 'de.inetsoftware:SetupBuilder:+'
    }`
to:
`dependencies {
        classpath 'de.inetsoftware:SetupBuilder:1.6.0-SNAPSHOT'
    }`

Now run "gradle msi" and it will build a .msi file for the testBuilds project in your distributions folder:
C:\Users\Leejjon\IdeaProjects\SetupBuilder\testBuilds\build\distributions

I will add a sample project on github soon. We should make a new ticket in supporting gradle 3.0.

**Comment by Horcrux7** [comment]
Sorry for the delay in answering. I was in holiday.

> My  guess was that I have to run "gradle msi" to start generating an installer

This is right.

If you receive a 

> java.lang.NoClassDefFoundError:  org/gradle/internal/file/PathToFileResolver

with an internal class then you use a Gradle version with an incompatible change. This occur currently frequently because Gradle is under heavy development.

> It would be nice to have a separate hello world java project using the setupBuilder gradle plugin

Which problem you have with the sample on the home page?

> Clone the SetupBuilder

What you want to do? If you want use the plugin then does not need to fork it. Else you want to modify it.

> Install and install the Wix toolset (I seem to have both WiX Toolset v3.10.3.3007 and v4.0.4305.0 installed, not sure which one it uses:

You see it on the log output which is used. The plugin detect it with an environment variable. The version 4.x of WIX was not tested.

> Open IntelliJ

IntelliJ should already support Gradle. There should no need for a manual installation.  But I does not use this IDE.

> Now rename the testBuilds/setupBuilder.gradle to build.gradle, and navigate into the testBuilds folder in your terminal by typing "cd testBuilds".

This is some code for internal testing. This is not a sample.

**Comment by Leejjon** [comment]
Thx for replying. I cloned your repo and tried to set it up in IntelliJ to figure out what made me get the error (so I could browse through the classes and see exactly where it went wrong). I could really not find any open source projects on github that use this plugin. I feared my error might have been caused by something in my configuration. That's why I tried to run the gradle files in your testBuilds example, it was the only project on github that worked. But as you said it's just Gradle evolving a bit fast.

A sample project or documentation mentioning that Gradle 2.14+ isn't supported would have saved me some time. But it wasn't too bad either diving into how Gradle plugins work. Good thing about open source is that I could figure it out :)

**Comment by Leejjon** [comment]
Here's my attempt on a sample project:
https://github.com/Leejjon/SetupBuilderDemo

It currently creates a shortcut but that still links to a .exe (while my executable is still a .jar). I still want to test it on a machine with no Java installed so I can see if it can use the bundled JRE correctly.

**Comment by gamma** [comment]
I'd like to resolve the issue since a demo has been provided.
