### ISSUE TITLE
Not support Gradle 2.14 or higher

### ISSUE THREAD

**Issue by TracelessDream** [i-net-software/SetupBuilder#29]
Seems that DefaultExecAction  has been deprecated since Gradle 2.14 which will cause java.lang.NoSuchMethodError exception in AbstractBuilder.java line 101.

**Comment by Horcrux7** [comment]
Add fix a https://github.com/i-net-software/SetupBuilder/commit/fa46b7a77f81c657a6700cd33e167bdb626275b0

**Comment by Horcrux7** [comment]
For Gradle 2.14 you can use plugin version 1.7. For version 3.0 you can use plugin version 1.8 now.
