### ISSUE TITLE
How to specify installdir location?

### ISSUE THREAD

**Issue by frankbarbarino** [i-net-software/SetupBuilder#35]
I'd like to specify my installation directory location (in my case for an MSI but I guess this would apply for any software type).   I haven't found a property to be able to set this.   It looks like the default location is based on the architecture and application name which sets it to: C;|Program Files\MyApplication when it tries to install.
1.   I would like to be able to specify the location to add in the vendor before the app name (or better still, supplying my own path as the default instead of it being built for me).      
for example:    C:\Program Files\MyCompany\MyProductSuite\MyApp.
2.   If possible, I would like to disable changing this location during installation.

SEEMS like pretty standard installer stuff to specify an install dir.    But I haven't found the option in the plugin.

**Comment by JasonAtTR** [comment]
Hi @frankbarbarino , have you tried the "wxsTemplate"? 
Any way you can write a template.wxs and put your installdir in your template as follows:
`<Property Id="INSTALLDIR" Value="please input your install dir" />`
then write your gradle code as follows:
```
msi {
    wxsTemplate = "${your_path}/template.wxs"
}
```

**Comment by Horcrux7** [comment]
This is only possible with the wxsTemplate property. See the [wiki](https://github.com/i-net-software/SetupBuilder/wiki/Create-a-MSI-with-WSX-template) for details.

**Comment by MatthiasZerau** [comment]
Quite late, but for reference I've used the following successfully:

```xml
<?xml version="1.0" encoding="windows-1252"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
  <Product>
    <SetProperty Id="INSTALLDIR" Value="[ProgramFiles64Folder]MyCompany\XyzService" Sequence="first" Before="CostFinalize">NOT Installed AND NOT INSTALLDIR</SetProperty>
  </Product>
</Wix>
```
