### ISSUE TITLE
Can we remove the log message 'setting default Destination to: ...'?

### ISSUE THREAD

**Issue by TracelessDream** [i-net-software/SetupBuilder#38]
No matter whatever task to run, this plugin will print below message to console.:
```
setting default Destination to: path/to/project/build/distributions
```

I guess this happens in the initialization or configuration phase of gradle's life cycle. I'm frustrated when I try to use other tools to consume the gradle task's output. I don't think it's a good practice to log message by using `System.out.println` in a gradle plugin.
Anyway, can we remove this log message or change it to debug level instead of print it to console directly?
 Thanks in advance!

**Comment by gamma** [comment]
The issue should be resolved now.
