### ISSUE TITLE
Debian control file getting application value where description value should be

### ISSUE THREAD

**Issue by hepcat72** [i-net-software/SetupBuilder#44]
I have the following defined:

```
setupBuilder {
    vendor = 'Princeton University Bioinformatics Group'
    application = "treeview3"
    appIdentifier = "treeview-3"
    icons = 'src/main/resources/TreeView3.icns'
    version = getVersionName()
    licenseFile = 'LICENSES/LICENSE'
    description = "Clustering heatmap viewer"
    from ( 'build' ) {
        include 'libs/*.jar'
    }
    bundleJre = 1.7
    mainClass = 'edu.stanford.genetics.treeview.app.TreeView3'
    mainJar = 'TreeView3.jar'
    desktopStarter {
        displayName = 'treeview3'
        executable = "treeview3"
    }
}

deb {
    maintainerEmail = 'treeview@princeton.edu'
}
```

However lintian errors out on the control file, which gets this:

```
Package: treeview-3
Version: 5beb153
Section: Applications/Productivity
Priority: optional
Architecture: all
Installed-Size: 2281
Recommends: openjdk-8-jre | openjdk-8-jdk | default-jre | default-jdk, libgtk2-perl
Pre-Depends: debconf
Maintainer: Princeton University Bioinformatics Group <treeview@princeton.edu>
Description: treeview3
 Clustering heatmap viewer
```

If I change the value for 'application', the value for Description changes.  I can't figure out how to fix it.  I tried writing a script to change it after the fact, but either it runs too early, or too late (after lintian has errored out).  Any suggestions?

**Comment by gamma** [comment]
Please note: the Description is a multiline field. The first line contains the application name, the following line the description. You could also set a long description using a localized resource file

The Description in your case is:

    Description: treeview3
     Clustering heatmap viewer

Do you have an error output of the lintian that you can give us?

**Comment by gamma** [comment]
Ok, it seems to be the same problem as #43 

The description starts with the same content as the pkg name. We're therefore chaining the description field in the control file to contain only the description and long description.
