### ISSUE TITLE
Exe created by Launch4j requires exact jre version

### ISSUE THREAD

**Issue by joeha480** [i-net-software/SetupBuilder#45]
I am using SetupBuilder version 1.8.0 and it appears that an exact match for the jre is required for the executable to start (e.g. 1.8.0_60). Having a later jre version doesn't work. Note that if you have multiple jres installed, the executable will select the correct version if available. 

The launch4j configuration doesn't specify maxVersion, so I have no idea what the problem could be.

Also, it would be nice if the minVersion for jre in launch4j could be set.

**Comment by Horcrux7** [comment]
Which error do you receive at which point? How you have set the Java version. Please write a little more details to understand your problem.

We use current update version 152 without problems.

**Comment by joeha480** [comment]
I'd be happy to try a newer version, but I cant due to #46.

I can't set the java version from build.gradle as far as I know. I tried to configure this because when I browse your code it indicates to me that it should be possible to set (however, I don't know if this capability existed in 1.8.0 or not and, as I've said, I can't update):
```gradle
launch4j {
  jre {
    minVersion = '1.8.0_40'
  }
}
```
The only way I know how to modify the version specified in the launch4j xml (generated by SetupBuilder) is to set JAVA_HOME before running gradle. This way, that java version will be used. However, I get this error dialog from Launch4j when starting the application, saying that the application requires java 1.8.0_60 (for example) even when I have a later version installed. 
![java](https://user-images.githubusercontent.com/4577802/32828387-37212a94-c9ef-11e7-88c4-3678ccdc7703.png)
When I click OK, it then opens a browser for me to download Java.

The launch4j xml that created this error:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launch4jConfig>
  <headerType>gui</headerType>
  <dontWrapJar>true</dontWrapJar>
  <classPath>
    <mainClass>application.MainFx</mainClass>
    <cp>lib/dotify-studio-0.5.0.jar</cp>
  </classPath>
  <outfile>[local path]\build\tmp\msi\dotify-studio.exe</outfile>
  <errTitle>Dotify Studio</errTitle>
  <chdir>.</chdir>
  <icon>[local path]\ant-build\resources\app-icon.ico</icon>
  <jre>
    <minVersion>1.8.0_60</minVersion>
    <runtimeBits>64</runtimeBits>
  </jre>
  <versionInfo>
    <fileVersion>0.5.0.0</fileVersion>
    <txtFileVersion>0.5.0</txtFileVersion>
    <productVersion>0.5.0.0</productVersion>
    <txtProductVersion>0.5.0</txtProductVersion>
    <fileDescription>Creates, manages and embosses PEF-files</fileDescription>
    <productName>Dotify Studio</productName>
    <companyName>DAISY Consortium</companyName>
    <copyright>© Copyright 2017 by DAISY Consortium</copyright>
    <originalFilename>dotify-studio.exe</originalFilename>
    <internalName>dotify-studio</internalName>
  </versionInfo>
  <manifest>[local path]\build\tmp\msi\launch4j6902712386786967780.manifest</manifest>
</launch4jConfig>
```

I have version 1.8.0_151 (64-bit) installed.

Ps. I don't understand what version 152 is.

**Comment by gamma** [comment]
FYI:
> Ps. I don't understand what version 152 you are referring to.

He ment `1.8.0_152`

**Comment by gamma** [comment]
#46 has been fixed. Can you please re-evaluate and let us know what you think is missing or should be changed?

**Comment by joeha480** [comment]
I am using 3.4.3 mentioned in #46. However, I don't think this issue has to do with that. Reading the conversation above, I think we misunderstood each other. I was referring to the requirement imposed by the exe file created by Launch4j. It's not about the java requirement on the packaging process itself, it's about the java requirement on the result of the packaging.

After installing the package on Windows, I get the above error message from the exe file created by SetupBuilder. To reproduce this error, you need to have two different computers with different versions of the JRE installed (or uninstall the version that you used to build the exe file with SetupBuilder). If you build the exe file with 1.8.0_60 (for example), you cannot run with 1.8.10_151.

I am reluctant to test it again at this time, because I am currently running Launch4j with another plugin. Also, I am moving towards embedding the JRE, so I don't need this anymore anyway. Lastly, since you don't appear to understand the problem, I have no reason to think that it has been fixed.
