### ISSUE TITLE
Make it possible to configure requestedExecutionLevel in launch4j manifest

### ISSUE THREAD

**Issue by joeha480** [i-net-software/SetupBuilder#47]
If it were possible to configure requestedExecutionLevel, I could avoid getting a warning every time the application is started on Windows 10. Perhaps there is another way (signing?), but changing the level to "asInvoker" seems to work.

**Comment by Horcrux7** [comment]
Which warning do you means?

**Comment by joeha480** [comment]
The in the launch4j manifest elevated permissions are required:
```xml
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
      </requestedPrivileges>
    </security>
```

The warning is from "User Account Control" asking the user if it's ok for an unsigned application to make changes on the device (my Windows is in Swedish, so I am not sure about the exact wording in English).

**Comment by gamma** [comment]
Did d3f355c help with your issue? Since there is a commit, I'd close this issue ...

**Comment by joeha480** [comment]
I am currently using another plugin for running Launch4j so I can't verify, but from your commit it appears to be solved. Thanks.
