### ISSUE TITLE
bundleJre on Linux

### ISSUE THREAD

**Issue by joeha480** [i-net-software/SetupBuilder#51]
SetupBuilder does not appear to bundle a jre on Linux.

**Comment by gamma** [comment]
That is correct. We advise to create a dependency to java and ask the user to install java on their own.

**Comment by joeha480** [comment]
I am sure that's good advice, but still I find it disappointing that an option which has no effect on some platforms is perceived as correct. Wouldn't it be better if the option did what it should on all platforms? Then, if the user doesn't want to bundle the jre on some platforms (perhaps because they're following an OS-specific guideline), they could just set bundleJre to false for those platforms.
