### ISSUE TITLE
Run on current gradle (version 4.5.1)

### ISSUE THREAD

**Issue by joeha480** [i-net-software/SetupBuilder#52]
SetupBuilder doesn't work on the current version  of gradle.

**Comment by gamma** [comment]
Which version of setup builder did you use? There are different versions depending on your gradle version.

**Comment by gamma** [comment]
I'm about to fix the issue

**Comment by gamma** [comment]
Ok, please check the latest version from the repository. You'll need to build it on your own before we submit a new version.

**Comment by joeha480** [comment]
It works, thanks!
