### ISSUE TITLE
How to copy extra files to the install location in an MSI

### ISSUE THREAD

**Issue by hepcat72** [i-net-software/SetupBuilder#55]
I realize this is likely a dumb question, but I'm a gradle newbie.  I had my gradle script create a .bat and a .vbs file so that our users could edit the java flags in the .bat script.  The files are created, and if I manually drag them into where the msi puts the jar file, they work... but how do I get gradle to have the msi setup wizard put them in that directory?  Here's my msi task where I create the files:

```
msi {
  def jarfile = 'treeview3' + '-all-' + getVersionName() + '.jar'
  setupBuilder.desktopStarter {
    displayName = 'TreeView3'
    executable = 'TreeView3.vbs'
  }
  doLast {
      //From https://stackoverflowcom/questions/38275583/
      from files(new File("$projectDir/build/tmp/msi/TreeView3.bat").text = """
@echo off\r
"%JAVA_HOME%\\bin\\java.exe" -Xmx4g -jar "${jarfile}"
"""
        ,
        //From https://superuser.com/questions/233348/
        new File("$projectDir/build/tmp/msi/TreeView3.vbs").text = """
Set WshShell = CreateObject("WScript.Shell")\r
WshShell.Run chr(34) & "TreeView3.bat" & chr(34), 0\r
Set WshShell = Nothing
"""
      )
      into "${projectDir}"
  }
}
```

Or perhaps I don't even need to do this?  Is there a way to get setupBuilder to automatically create launcher scripts that have the java command with flags that I can set (e.g. '-Xmx4g')?

**Comment by Horcrux7** [comment]
You can add it with a from tag like:
```
msi {
    // files only for the Windows platform
    from( 'myScriptSourceDir' ) {
       include '*.bat'
       include 'TreeView3.vbs'
    }
}
```

**Comment by hepcat72** [comment]
OMG that worked!  Thanks a bunch.  I don't know why I was determined to create the files in the gradle script.
