### ISSUE TITLE
DEB and RPM should respect the bundleJRE setting

### ISSUE THREAD

**Issue by RobertStroud** [i-net-software/SetupBuilder#56]
The DEB and RPM scripts ignore the bundleJRE setting and never produce a package with an embedded JRE. Given that Oracle now recommend embedded JREs for deployment, this should be reconsidered. 

>"Over the past decade, vendors of the most popular desktop operating systems have emphatically pushed for applications on their platforms to be delivered bundled with integrated, sandboxed runtimes. [...]
> The notion of an application being distributed separately from a standalone JRE is, therefore, quickly fading.

http://www.oracle.com/technetwork/java/javase/javaclientroadmapupdate2018mar-4414431.pdf

**Comment by joeha480** [comment]
See also: #51

**Comment by gamma** [comment]
We definitely look into this. I can't promise when exactly but I think it will be done this summer.

**Comment by gamma** [comment]
Actually ... no. As I said: will have to look into this ;)

**Comment by gamma** [comment]
The latest releases supports bundleJRE for rpm and deb tasks. Please check it out.
