### ISSUE TITLE
Unable to run *.app file

### ISSUE THREAD

**Issue by iromeo** [i-net-software/SetupBuilder#57]
Hi, I cannot launch created *.app file, I always get some error. I tried two ways

1. If I add `bundleJre = 1.8` into `appBundler`, I get **"Unable to load Java Runtime Environment."** error while launching `appBundlerTestBuild.app`

2. If I don't bundle jre, I get
```
LSOpenURLsWithRole() failed with error -10810 for the file /Users/[...]/build/distributions/appBundlerTestBuild.app.
```

P.S. I created small example based on samples. My `bundleApp` app tasks depends on `shadowJar` tasks which creates *.jar files with all necessary things. I can launch may jar file using `java -jar dev-build.jar`. My appBundler config is
```
appBundler {
    application = "appBundlerTestBuild"
    description = 'Build a test programm.'
    icons = "${project.buildDir}/resources/main/icons/some.icns"

    from shadowJar.outputs

    bundleJre = "1.8"
    mainClass = 'org.foo.Main'
    mainJar = 'dev-build.jar'
}

import org.apache.tools.ant.taskdefs.condition.Os
bundleApp {
    dependsOn shadowJar
}
```

**Comment by iromeo** [comment]
P.S: I've checked that https://github.com/crotwell/gradle-macappbundle plugin works or, with/without bundling java, but I'd like to have solution, which also covers Linux & Windows

**Comment by gamma** [comment]
Can you please check the latest release?

**Comment by iromeo** [comment]
Thanks, I’ll try it next week, I’ve alredy rewritten my code to use other plugins..
