### ISSUE TITLE
RTF text license conversion bug

### ISSUE THREAD

**Issue by sheinbergon** [i-net-software/SetupBuilder#61]
In the [WxsFileBuilder](https://github.com/i-net-software/SetupBuilder/blob/1f5e7dd3ad0336ef2a81dc5a15893d20d03cfb21/src/com/inet/gradle/setup/msi/WxsFileBuilder.java) class, you have this code:
```java
try( FileInputStream fis = new FileInputStream( license ) ) {
  byte[] bytes = new byte[5];
  fis.read( bytes );
  isRtf = "{\rtf".equals( new String( bytes ) );
}
```
I'm pretty sure you double escape `\r`.  This equality check fails, causing RTF files to be RTF escaped twice, resulting in a malformed RTF license.

**Comment by Horcrux7** [comment]
Was fix in 820a5be204096b011d6fbec503ad09838964938b
