### ISSUE TITLE
Support jlink images

### ISSUE THREAD

**Issue by Burtan** [i-net-software/SetupBuilder#66]
Hi, 
when using the new deployment system for the JPMS there is no more .jar file which has to be declared, it is rather a script. Maybe remove that dependency?
Best Burtan

**Comment by Horcrux7** [comment]
Can you be more specific what do you want?

How should look your Gradle script and what you expect as result of SetupBuilder?
Which errors do you receive if you try it currently? Or which problems do you see?

Sorry for the simple questions but we have not use jlink for a completely application currently.

**Comment by Burtan** [comment]
I'm right now strugling with #60 so I can't say which problems will come but e.g. the output from jlink produces an executable script and some runtime files. There is no .jar anymore which could be defined. So this option should not be forced anymore.

**Comment by gamma** [comment]
Hello Burtan, we're in the process of it. Our current solution is to fetch the required VM which is created by jlink in an extra process and package it. SetupBuilder does not use modules in this case but plain old jar files - no change here. The only change is where the VM comes from - we're going to use custom build of the AdoptOpenJDK.

**Comment by gamma** [comment]
Hello Burtan, the current release supports link images. You still just have to define the home folder of the JRE. You still have to download it and so on. As stated above we're having scripts to do all of this in our build environment. Do you require further assistance from the SetupBuilder plugin?
