### ISSUE TITLE
Gradle daemon + i18n: AccessDeniedException

### ISSUE THREAD

**Issue by narkaTee** [i-net-software/SetupBuilder#67]
Hi,

Version: 4.8.5

there is a problem with the i18n change from 904cd70d67ea795b999ca686180aa03be4b4b518 when running with the gradle daemon.
If you run the msi task twice on the same gradle daemon an exception (`AccessDeniedException`) is thrown during buildscript evaluation.
Stacktrace [here](https://pastebin.com/mWLw4sDB).

I suspect there is a left over file handle which prevents write access to the target file of `ResourceUtils.extract`.

The `TempPath` util is part of the problem, it uses a static variable to store the temp path:
https://github.com/i-net-software/SetupBuilder/blob/93d5f6730d27bb937651bf9194c59898a51877cd/src/com/inet/gradle/setup/util/TempPath.java#L20-L45

Thath causes `ResourceUtils.extract` to write to the same file as the build before
https://github.com/i-net-software/SetupBuilder/blob/93d5f6730d27bb937651bf9194c59898a51877cd/src/com/inet/gradle/setup/util/ResourceUtils.java#L51-L58

Repo with reproduction: https://github.com/narkaTee/setupbuilder-issue67-repro

**Comment by narkaTee** [comment]
Any plans to release this? It would be nice to get rid of the "daemon killing" workaround. 😉

**Comment by Horcrux7** [comment]
Should be available now.
