### ISSUE TITLE
Linux file permissions during copy are changed

### ISSUE THREAD

**Issue by Burtan** [i-net-software/SetupBuilder#68]
Hi,
I've got problems with the file permissions during copy. Adding fileMod or dirMode doesn't help. I need an executable permission on the startup script generated by jlink.

**Comment by janosvitok** [comment]
If you still follow: does this patch help? https://github.com/WhitesteinTechnologies/SetupBuilder/commit/abda559cf4548c2bdc494ed0ffbc942d8d5ecfb2

**Comment by Burtan** [comment]
Thanks for answering, however, I switched to jlink and jpackage.
