### ISSUE TITLE
Disable repair installation option

### ISSUE THREAD

**Issue by ErikShiken** [i-net-software/SetupBuilder#69]
Sorry I'm not sure where else to post this question.

I'd like to disable the repair installation option from setupBuilder. How do I do that?

**Comment by Horcrux7** [comment]
Do you means the Windows installer? You can search for [wix toolset disable repair](https://www.google.com/search?q=wix+toolset+disable+repair).

If you find a solution to do it with wix toolset then you set it via a [WSX template](https://github.com/i-net-software/SetupBuilder/wiki/Create-a-MSI-with-WSX-template).

The target of the SetupBuilder plugin are simple native installer for different platforms. It will not handle all the specific options that are possible for one platform.

**Comment by ErikShiken** [comment]
Oh ok. Thanks!
Erik
