### ISSUE TITLE
How to access INSTALLDIR from postinst vbscript?

### ISSUE THREAD

**Issue by micheljung** [i-net-software/SetupBuilder#71]
Does somebody know how to do it and could add some documentation, please? :-)

See also https://stackoverflow.com/questions/55917478/wix-setupbuilder-get-value-of-installdir-in-vbscript

**Comment by Horcrux7** [comment]
Already answered on stackoverflow.

**Comment by micheljung** [comment]
Is the SO answer really the intended solution? If so, it'd be nice if it was documented in this repository.
