### ISSUE TITLE
Generated file IDs not always unique

### ISSUE THREAD

**Issue by micheljung** [i-net-software/SetupBuilder#72]
Consider a directory structure like this:

    /foo_bar.txt
    /foo/bar.txt

Both result in the file ID `foo_bar.txt`, resulting in:

```
: error LGHT0091 : Duplicate symbol 'File:foo_bar.txt' found. This typically means that an Id is duplicated. Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.
: error LGHT0092 : Location of symbol related to previous error.
```

Another source for possible duplicates is the [file ID limit](https://github.com/i-net-software/SetupBuilder/blob/master/src/com/inet/gradle/setup/msi/WxsFileBuilder.java#L1290).

To avoid this, I suggest to generate UUIDs for each file and replace `-` with `_`, or simply use a counter.

**Comment by micheljung** [comment]
Apparently, [there's already code in place](https://github.com/i-net-software/SetupBuilder/blob/master/src/com/inet/gradle/setup/msi/WxsFileBuilder.java#L1307) to prevent this from happening but still, it happened. I'm using version `4.8.5`.

**Comment by Horcrux7** [comment]
SetupBuilder required to create a human readable, reproducible ID. You can set a template that then will be patch. That the IDs in the template must readable and reproducible. For example you can use a ID of a file in some other place that SetupBuilder can not handle.

Yes, the IDs are not 100% identical. But it was a compromise between correctness and simplicity. Changing this would break many installer from many users.

If the problem occur, you must have 3 files that match to the same ID. Is this right?

If you want really install files like `/foo_bar.txt` and `/foo/bar.txt` then SetupBuilder can not be the right tool for you.

Do you have a real problem or is this a result of a view in the source code?

**Comment by micheljung** [comment]
I'm trying to package [Kibana](https://www.elastic.co/products/kibana) as an MSI, specifically from their [Windows ZIP file](https://artifacts.elastic.co/downloads/kibana/kibana-7.0.1-windows-x86_64.zip).

During the packaging, the described problem occurred. But when I tried again, it didn't. I'll try again from scratch.

**Comment by Horcrux7** [comment]
Can you attach the file logstash-6.7.0.wxs?

**Comment by micheljung** [comment]
I tested the newest version of Logstash, 7.0.1. Here's `logstash-7.0.1.wxs`.

[logstash-7.0.1.wxs.zip](https://github.com/i-net-software/SetupBuilder/files/3140976/logstash-7.0.1.wxs.zip)

**Comment by Horcrux7** [comment]
Can you test it with the snapshot version? You can try it with:

```
buildscript {
  repositories {
    maven { url 'https://jitpack.io' } // for snapshot of the SetupBuilder
  }
  dependencies {
    classpath 'com.github.i-net-software:SetupBuilder:master-SNAPSHOT'
  }
}

apply plugin: "de.inetsoftware.setupbuilder"

setupBuilder {
....

```

**Comment by micheljung** [comment]
Thanks! Unfortunately, I'm behind a corporate Nexus proxy and I think jitpack is not configured as a remote. I'll ask if they can add it, though.

**Comment by Horcrux7** [comment]
Alternative you can build it self (task uploadArchives) and then use:

```
buildscript {
  repositories {
    maven { url "../repo" }
  }
  dependencies {
    classpath "de.inetsoftware:SetupBuilder:4.8.6-SNAPSHOT"
  }
}

apply plugin: "de.inetsoftware.setupbuilder"
```

**Comment by micheljung** [comment]
Works like a charm, thank you for your effort ❤️
