### ISSUE TITLE
Packaging JRE 11

### ISSUE THREAD

**Issue by GregJohnStewart** [i-net-software/SetupBuilder#73]
I think I almost have a working deb, but when I build it, it shows the following warning:

`bundleJre version '1.11' can not be resolved to a Java Runtime Directory which is required for embedding!`

I have jre 11 installed, and that is what the project builds to be compatible for. 

Configuration in build:
```groovy
setupBuilder {

    vendor = 'Greg Stewart'
    appIdentifier = "TaskTimekeeper"
    version = version

    application = "Task Timekeeper"
    description = 'A program for keeping track of time spent on tasks.'
    icons = "src/main/resources/test-icon.icns"

    licenseFile "../LICENSE"

    from jar.outputs

    bundleJre = 1.11
    mainClass = mainClassName
    mainJar = 'BaseCode-1.0.jar'

}
```

I am trying to use the outputs from the Application gradle plugin. Currently, this still created a .deb file, but when installed I cannot seem to see it either from the command line or Ubuntu's application explorer. Any hints towards that also appreciated.

**Comment by Horcrux7** [comment]
Setting a Java version does not work for the Unix platform. Set a path to your Java installation that should be bundled. 

Or suggest a patch for [Unix.java](https://github.com/i-net-software/SetupBuilder/blob/master/src/com/inet/gradle/setup/unix/Unix.java).
