### ISSUE TITLE
Creating .deb makes debian package that doesn't appear in system when installed

### ISSUE THREAD

**Issue by GregJohnStewart** [i-net-software/SetupBuilder#75]
Hello all,

I am trying to get a debian (.deb) installer working on a debian system (Ubuntu), but when I run the `deb` task, it creates a .deb file that when installed doesn't provide the command to run in terminal. I could be missing something small here, but there are limited docs on this project.

My configuration of setup builder:

```
setupBuilder {

    vendor = 'Greg Stewart'
    appIdentifier = applicationName  // "TaskTimekeeper"
    this.version = version // '0.1'

    application = "Task Timekeeper"
    description = 'A program for keeping track of time spent on tasks.'
    icons = "src/main/resources/test-icon.icns"

    licenseFile "../LICENSE"

    from jar.outputs

    //bundleJre = 1.11 // not working on linux systems :(
    mainClass = mainClassName // "com.gjs.taskTimekeeper.desktopApp.Main"
    mainJar = 'DesktopApp-0.1.jar'

}
```

Result (after installing the created debian):

```
$> tasktimekeeper
tasktimekeeper: command not found
```

**Comment by gamma** [comment]
Hello Greg; The setup builder provides a means of installing the software as given. It does not create binaries or link them to bin directories - what I think you were expecting.

You have to create the binaries or link scripts to bin directories as needed. For desktop applications you can create shortcuts to your binaries using a "desktopStarter" section.

The `deb` target supports multiple `postinst` scripts that can move/link binaries as needed.

I'll try to improve the documentation side.

**Comment by GregJohnStewart** [comment]
@gamma Thanks for getting back to me! An example in the docs would be fantastic, though I think I have worked through this issue.

**Comment by gamma** [comment]
I updated the docs to a great deal today to have the options of the tasks available - but some more explanation will be needed.

Setup Builder does not create fat jars. You will have to add your jar dependencies as sources to setupBuilder and make sure they are referenced in the Manifest or as classpath option.

**Comment by GregJohnStewart** [comment]
Thanks for updating the docs, it is much appreciated. Using this with the application plugin seems like a common enough use case, if/when I figure out how to get it working I'll let you know and maybe we can get a bit of documentation just for that.

**Comment by gamma** [comment]
👍 thanks!

**Comment by GregJohnStewart** [comment]
Made a new wiki page here: https://github.com/i-net-software/SetupBuilder/wiki/How-to-create-setup-of-desktop-application-using-with-the-Gradle-Application-plugin

Thanks again for the help!
