### ISSUE TITLE
Fix 'delayed' startup

### ISSUE THREAD

**Issue by micheljung** [i-net-software/SetupBuilder#82]
In https://github.com/i-net-software/SetupBuilder/pull/80 I thought the value is passed to procrun, when in fact it's passed to the WXS file.

```
: error CNDL0021 : The ServiceInstall/@Start attribute's value, 'delayed', is not one of the legal options: 'auto', 'demand', or 'disabled'.
```

I'll see how it can be fixed.

**Comment by Horcrux7** [comment]
I think you need to add a ServiceConfig https://wixtoolset.org/documentation/manual/v3/xsd/wix/serviceconfig.html

This can look like: 
```
Element config = getOrCreateChildById( install, "ServiceConfig", id + "_config" );
addAttributeIfNotExists( config, "DelayedAutoStart", "yes" );
```
But you should test it if this work.

**Comment by Horcrux7** [comment]
Any news on it?
