### ISSUE TITLE
Doesn't seem to work with gradle 6?

### ISSUE THREAD

**Issue by tomqwpl** [i-net-software/SetupBuilder#85]
I've just tried this in a gradle 6 project. 
First issue is the automatic version select script isn't supported (can't have anything before the plugin block). But that's fine, I can just reference a version manually.

However, I then get:

An exception occurred applying plugin request [id: 'de.inetsoftware.setupbuilder', version: '4.8.6']
> Failed to apply plugin [id 'de.inetsoftware.setupbuilder']
   > Could not create task ':wpshub:deb'.
      > Could not create task of type 'Deb'.
         > Could not generate a decorated class for class com.inet.gradle.setup.unix.deb.Deb.
            > org/gradle/internal/nativeplatform/filesystem/FileSystem

So it looks like the plugin isn't compatible with gradle 6?

Thanks.

**Comment by Horcrux7** [comment]
We will check this.

**Comment by Horcrux7** [comment]
Can you please try the snapshot version with Gradle 6 with the follow code:

```
buildscript {
  repositories {
    maven { url 'https://jitpack.io' } // for snapshot
  }
  dependencies {
    classpath 'com.github.i-net-software:SetupBuilder:master-SNAPSHOT'
  }
}
apply plugin: "de.inetsoftware.setupbuilder"
```

If it not working then we need possible stacktraces.

**Comment by tomqwpl** [comment]
OK, thanks for the swift response. It certainly now loads up. Can't say further than that, as we'll have to actually start making use of it in anger, but my guess is that that's fixed it.
thanks.
