### ISSUE TITLE
Produce multiple CAB files if necessary

### ISSUE THREAD

**Issue by micheljung** [i-net-software/SetupBuilder#88]
Building an application with more than 65535 files causes this error:

    light.exe : error LGHT0306 : An error (E_FAIL) was returned while finalizing a CAB file.
    This most commonly happens when creating a CAB file with more than 65535 files in it.
    Either reduce the number of files in your installation package or split your installation
    package's files into more than one CAB file using the Media element.

**Comment by Horcrux7** [comment]
I does not know if this is possible with a msi file. I also does not see many sense in it. Our own setup has fewer as 1000 files. But you are free to make a PR.

**Comment by Horcrux7** [comment]
Won't fix.
