### ISSUE TITLE
Allow use of other JDK distributions

### ISSUE THREAD

**Issue by arlllk** [i-net-software/SetupBuilder#94]
Currently if one put `bundleJre = 1.8` or `bundleJre = 1.11` on windows search in `C:\Program Files\Java`, the problem is that I have AdoptOpenJDK and also OpenJDK, but it doesn't detect those distributions.

Idea:
A)
In windows use the **where** command, it can find all the locations of JDK in the PATH
`where.exe java`
output: 
```
C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-15.0.0.36-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot\bin\java.exe
C:\Program Files\OpenJDK\openjdk-11.0.8_10\bin\java.exe
```
Pros: 
- The [where command](https://ss64.com/nt/where.html), its included in windows since windows XP
- Its very portable (It can find from other computers and other languages, or non standard installations)

Cons:
- Parse command output

B)
Let set the start path where one can start search (change the variable that is set to `C:\Program Files\Java`)

Let set `basePath = "C:\Program Files\AdoptOpenJDK\"`

Pros:
- very easy to integrate

Cons:
- Not very portable, (If someone has a distinct distribution. Example: (AdoptOpenJDK or OpenJDK)

**Comment by arlllk** [comment]
For the case A, the regex that can select the mayor version of OpenJDK, AdoptOpenJDK, Corretto and Zulu) is

`(?<=jdk-)([1]?[1-9])(?=\.)|(?<=jdk1\.)([1]?[1-9])(?=\.)|(?<=zulu)([1]?[1-9])(?=\\)`

tested on 

```
C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-15.0.0.36-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot\bin\java.exe
C:\Program Files\OpenJDK\openjdk-11.0.8_10\bin\java.exe
C:\Program Files\Amazon Corretto\jdk1.8.0_252\bin\java.exe
C:\Program Files\Zulu\zulu8\bin\java.exe
```

**Comment by Horcrux7** [comment]
You can set the path to the JDK that you want to bundle like:
```
bundleJre = 'C:\Program Files\OpenJDK\openjdk-11.0.8_10\'
```

The idea of a central installed and registered Java is outdated.

**Comment by arlllk** [comment]
> The idea of a central installed and registered Java is outdated.

That's why I think that have the path hard coded should be changed, to get the correct path dynamically

**Comment by Horcrux7** [comment]
> That's why I think that have the path hard coded should be changed, to get the correct path dynamically

I does not understand what you means. You can already set the path to the JDK that you want bundle.

The larger problem is not the base directory else the version matcher. The version does not follow a fix rule anymore. On my system I have:

```
jdk-11
jdk-11.0.7
jdk-14+36
jdk-15
jdk1.8.0_171
jdk8u232-b09
jre1.8.0_191

```
But I have also see only a number and starting with `java`.

**Comment by gamma** [comment]
Since you can already define which JVM to use, this is a non-issue.
