### ISSUE TITLE
DMG: how to add a .jnilib to the /foo.app/Contents/MacOS folder?

### ISSUE THREAD

**Issue by PatrickWegmann** [i-net-software/SetupBuilder#97]
how do i include a native lib so that it can be found by the Application in the /foo.app/Contents/MacOS instead of the /foo.app/Contents/Java directory?

**Comment by PatrickWegmann** [comment]
i hacked in a Property to make i do what i need 

`        if (setup.getNativeLibDir() != null) {
            String nativeDir = (String)setup.getNativeLibDir();
            File file = Paths.get(nativeDir).toFile();
            if (file.isDirectory()) {

                FileSet fileSet = new FileSet();
                fileSet.setDir(file);
                appBundler.addConfiguredLibraryPath(fileSet);
            }
        }`


copyLibraryPathEntries(File macOSDirectory)

**Comment by gamma** [comment]
Could you transform this into a pull request?

**Comment by gamma** [comment]
Please check the proposed solution and let me know if it works for you.
