### ISSUE TITLE
Bundled JREs > 11 dont work on OSX

### ISSUE THREAD

**Issue by PatrickWegmann** [i-net-software/SetupBuilder#98]
the native JavaAppLauncher has #define LIBJLI_DY_LIB "lib/jli/libjli.dylib" hard coded. in newer JRE versions the libjli.dylib is just in lib, can some one compile a new JavaAppLauncher please, cause i couldn't compile it on a new OSX Catalina. thank you so much

**Comment by PatrickWegmann** [comment]
Ok, i managed to compile a new version, i some one interested, see attachment

[JavaAppLauncher.zip](https://github.com/i-net-software/SetupBuilder/files/6492455/JavaAppLauncher.zip)

**Comment by gamma** [comment]
How did you update the source code and build script to build the JavaApplicationLauncher?

**Comment by PatrickWegmann** [comment]
HI

> 
> 
> How did you update the source code and build script to build the JavaApplicationLauncher?

i chucked the .m into an xcode project and built it, but there is an other problem. if i download the unsigned app .dmg from the internet the gatekeeper doesn't seem to like it, so the user gets the message that the app is corrupted. So I'm not sure if it's the JRE (im using bellsoft jre 14 which is signed) or the new complied AppLauncher, the only way to bypass this nonsense is to sudo xattr -cr /Applications/MyApplication.app, if i install the app locally  from the dmg (not downloaded through a browser) it works fine. I would greatly appreciate any help on this issue. If you like i can send you the xcode project.

**Comment by gamma** [comment]
Yes, please send me the project. Did you codesign the final dmg and submit it to the stapeling process by Apple?

**Comment by PatrickWegmann** [comment]
> 
> 
> Yes, please send me the project. Did you codesign the final dmg and submit it to the stapeling process by Apple?

no i didn't go through that hell yet, I'm still in the beta phase of my project.
[JavaAppLauncher2.zip](https://github.com/i-net-software/SetupBuilder/files/6502244/JavaAppLauncher2.zip)

**Comment by PatrickWegmann** [comment]
btw have you got any plans to incorporate a pkg installer for mac?

**Comment by gamma** [comment]
Thanks.

The package installer is available for server-like components.

**Comment by gamma** [comment]
You have to add a service in order to create a package installer.

**Comment by PatrickWegmann** [comment]
> 
> 
> You have to add a service in order to create a package installer.

ah i see, and this would work to install just an app? I'll have to figure it out i guess.

**Comment by gamma** [comment]
I think the experience would not be good at the moment. You probably want to install a desktop app with additional scripts being run during installation?

A service comes with an additional preferences panel and daemon settings to automatically run the service etc.

**Comment by PatrickWegmann** [comment]
Ok, now if i create an installer package, i used http://s.sudre.free.fr/Software/Packages/about.html , i can bypass the "Application is damaged and can't be opened. You should move it to the Trash." without having my test users to type commands into the terminal. So i would say the new JavaAppLauncher  for JDK 11+  should actually work. I will report back how it went with the signing process.

@gamma as i mentioned in an other issue, i built in a modification to SetupBuilder to include .dylib libs into the osx app, if you interested i can send you a patch.

**Comment by gamma** [comment]
@PatrickWegmann please submit a PR if possible. I'll try and add the code then.

**Comment by gamma** [comment]
Please check the new JavaAppLauncher.
